### ISSUE TITLE
ember-macro-helpers a required dependency?

### ISSUE THREAD

**Issue by crhayes** [kellyselden/ember-awesome-macros#326]
I'm in the process of upgrading to Ember 2.13, and in doing so updating this library from `0.31.0` to  `0.35.1`.

My application was broken without explicitly running `ember install ember-macro-helpers`. Is this supposed to be a required dependency? If so, we should update the documentation to reflect this.

**Comment by kellyselden** [comment]
It's not required unless you have something like `import raw from 'ember-macro-helpers/raw';' in your app. What npm/yarn version are you on? What is your error message?

**Comment by bartocc** [comment]
+1

my app works great with the following versions:

`ember --version`
```
ember-cli: 2.13.1
node: 7.7.3
os: darwin x64
```

`yarn list ember-awesome-macros`
```
yarn list v0.21.3
└─ ember-awesome-macros@0.34.0
✨  Done in 1.07s.
```

Then I `yarn upgrade ember-awesome-macros`:
```
yarn upgrade v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "broccoli-tslinter@2.0.1" has unmet peer dependency "typescript@^2.0.0".
warning "broccoli-tslinter@2.0.1" has unmet peer dependency "tslint@^4.0.2".
warning "broccoli-typescript-compiler@0.6.2" has unmet peer dependency "typescript@^1.6.2 || ^1.7.0 || ^1.8.0 || ^1.9.0-dev || ^2.0.0 || ^2.0.0-dev || ^2.1.0-dev || next".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ ember-awesome-macros@0.35.1
└─ ember-macro-helpers@0.14.0
✨  Done in 7.90s.
```

and I get the following error:
`Error: Assertion Failed: You attempted to define a `{{link-to "signup"}}` but did not pass the parameters required for generating its dynamic segments. _buildComputed.buildCurriedComputed is not a function@ 266 ms`

And in my signup controller, I have indeed:
`import notEqual from 'ember-awesome-macros/not-equal';`

Hope this helps

**Comment by crhayes** [comment]
@kellyselden I am using `raw` and `writable` the way you describe. It's weird because it was working before without me explicitly adding `ember-macro-helpers` as a dependency.

Here is the error:

![image](https://cloud.githubusercontent.com/assets/727536/25701468/87e3c93a-309a-11e7-82f6-1ad2e56da1ea.png)

**Comment by kellyselden** [comment]
I wasn't seeing your stack trace, but I did see an issue with `notEqual`. Fixed in #328. Could you try out v0.35.2 and see if that helps?

**Comment by bartocc** [comment]
@kellyselden I've juste tried v0.35.3, with no luck.

I also tried `import {notEqual} from 'ember-awesome-macros';` instead of `import notEqual from 'ember-awesome-macros/not-equal';`, but it still fails

**Comment by kellyselden** [comment]
I cannot recreate this with a brand new project. Is you version of ember-macro-helpers old? Can you run `npm ls ember-macro-helpers`?

**Comment by crhayes** [comment]
@kellyselden Regarding the issue with `notEqual`, I didn't experience it. However, I used Ember Twiddle to confirm there was an issue using `0.35.1`. It appears to be fine after testing with `0.35.2`.

**Comment by bartocc** [comment]
I'll try to setup a twiddle next week to reproduce my bug

Le ven. 5 mai 2017 à 21:29, Chris Hayes <notifications@github.com> a écrit :

> @kellyselden <http://clicks.crx.io/wf/click?upn=S8NtJlhzKsbL5BEVJrBaBTW-2F8OMwPFv4o5Zg6r4gZNlJQlTjsZ83L2v6vaRMpGS7_s5UH8bhnBaopYjthcNSRcR5-2BiAMgrjiX8nvyZD1gSh0xr1UhFYFSjxyXARfM2skQsdl9V0rZea7xlUTNpq2qrGtkfF51oIVfui0kXJy6TMovu5r6-2B-2Bezqp6859uF-2B5ATSxTpHA-2B3KPI8cD4neLqYLSIKDrYqetV6Q1H0eHCm9a1bUZLcgHMb2Kr7A4c6nOIz19jXLzNieUENOFvyqFd4X5BsSAwNxgrvVy6HDXTaGCwBtOAZQGp23L4IgM-2F9dMPWzYqpCwOKARgBB8ZX7uBhDF-2Fi2qx5QwxB6togADXv2jE11XPRcHn343SesHMBayE-2B4rR-2FEF4mwkVGBF9fGlzQgA-3D-3D> Regarding the issue with
> notEqual, I didn't experience it. However, I used Ember Twiddle to
> confirm there was an issue using 0.35.1. It appears to be fine after
> testing with 0.35.2.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <http://clicks.crx.io/wf/click?upn=S8NtJlhzKsbL5BEVJrBaBTW-2F8OMwPFv4o5Zg6r4gZNlQDw-2FBEW0JUK-2FUvvtu2QNV2hUtqWIqS4tyA3aEUi7ohOBTs02y5t6hjSfOh487tUK2v-2FizIqzF5VN0CFwY-2BKLY_s5UH8bhnBaopYjthcNSRcR5-2BiAMgrjiX8nvyZD1gSh0xr1UhFYFSjxyXARfM2skQsdl9V0rZea7xlUTNpq2qrGtkfF51oIVfui0kXJy6TMovu5r6-2B-2Bezqp6859uF-2B5ATSxTpHA-2B3KPI8cD4neLqYLSIKDrYqetV6Q1H0eHCm9a1bUZLcgHMb2Kr7A4c6nOIzpSuTRfJ0GFjwFHBU-2FBaaasAAXPmpXpLgXdnLXshHaUDIqlOKYaHUCYWbXGPSJFdbwlPkmDiALkt-2F9yQWExgTJ21VRc2oLeHWHJcgYjVJ6uXA7oINATYJZx1ZjFhLehE7IrxgWPlAu0vzTT3k0Q0MUA-3D-3D>,
> or mute the thread
> <http://clicks.crx.io/wf/click?upn=S8NtJlhzKsbL5BEVJrBaBSSbuIiZAgCCd1YT5JjUGl-2BNz90vdAsqQUu80bVdTYECwKs8xWCXn-2FTCGvrDuBfE-2Bbu9b4II2PKSVLEO-2F8T3yY-2BAT7yWGUyZPPytd5MrnLzwLwLPQ9bkSanllIUAXVxtHw-3D-3D_s5UH8bhnBaopYjthcNSRcR5-2BiAMgrjiX8nvyZD1gSh0xr1UhFYFSjxyXARfM2skQsdl9V0rZea7xlUTNpq2qrGtkfF51oIVfui0kXJy6TMovu5r6-2B-2Bezqp6859uF-2B5ATSxTpHA-2B3KPI8cD4neLqYLSIKDrYqetV6Q1H0eHCm9a1bUZLcgHMb2Kr7A4c6nOIzRFkukC8PZlKkKir9NuXPo3WbVO4dS1ez7pCo8WNMCjDgr5LGwRZcHk6OD-2Fx-2FLSFFkJsoizjAlXPGrWOKQ34OFoxtWVzwYUg6sJmSUicUIJ8SXqfqWSCoVLiKfUNZvfbGDI9JcRNBunVgprdNHxjWdg-3D-3D>
> .
>
-- 

-
[image: Julien Palmas]
<http://clicks.crx.io/wf/click?upn=S8NtJlhzKsbL5BEVJrBaBe-2FGEnkz6ZvSgIEFjbetRNnMXXsDx5s-2FniDMCo7Ru-2B9RItprvbmbGozkFV8muwzQ5QhB-2Fg7DHLQeEgGwXP4U76w-3D_s5UH8bhnBaopYjthcNSRcR5-2BiAMgrjiX8nvyZD1gSh0xr1UhFYFSjxyXARfM2skQsdl9V0rZea7xlUTNpq2qrGtkfF51oIVfui0kXJy6TMovu5r6-2B-2Bezqp6859uF-2B5ATSxTpHA-2B3KPI8cD4neLqYLSIKDrYqetV6Q1H0eHCm9a1bUZLcgHMb2Kr7A4c6nOIz5IhDWPJ-2BNKWFuKvNMO4TWBvf3MLyAXOhP1MkQvb2ShB13zNkzZwvfg79J2Wyj7U-2B5kf50SvBc7TxhRXKuunLScOV5wWkZWFAmrhNt2YvWD8n8zYB12ZKqkiEuBG1kQCPW37mTNz5igFuWOpv-2BlU-2BGg-3D-3D>

**Comment by bartocc** [comment]
Ok, to reproduce the bug with notEqual, simply add ember-moment 7.3.0 to your project.

On my project, `yarn list ember-macro-helpers` outputs

```
yarn list v0.23.4
├─ ember-macro-helpers@0.14.1
└─ ember-moment@7.3.0
   └─ ember-macro-helpers@0.4.0
✨  Done in 0.93s.
```

I've created https://github.com/stefanpenner/ember-moment/issues/237 to ask for a new release because the version of ember-macro-helpers has been updated in the latest ember-moment commits by @kellyselden

**Comment by snewcomer** [comment]
Upgrading ember-moment/ember-computed-decorators and ember-awesome-macros fixed the problem for me.  I believe this could be closed?  Anybody else having problems?

**Comment by kellyselden** [comment]
Closing as I believe the original issue is resolved.
